name: Check for broken links

on:
  schedule:
    - cron: '0 6 * * 3'

jobs:
  broken-links:
    runs-on: ubuntu-latest

    steps:
      - uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: "https://jeremy-faton.github.io"
          verbose: "true"
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
