name: Check for broken links

on:
  push:
    paths:
      - ".github/workflows/check-broken-links.yml"
  schedule:
    - cron: '0 6 * * *'

jobs:
  broken-links:
    runs-on: ubuntu-latest

    steps:
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "https://jeremy-faton.github.io"
